on:
  create

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rustext -> target"
    
    - name: Install Cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross
    
    - name: Build Linux
      run: cargo build -p webrtc-tunnel
    
    - name: Build Windows
      run: cross build --target x86_64-pc-windows-gnu -p webrtc-tunnel
    
    # - name: Build Mac Intel
    #   uses: Shogan/rust-musl-action@v1.0.2
    #   with:
    #     args: cargo build --target x86_64-apple-darwin
    
    # - name: Debug
    #   run: ls target/x86_64-apple-darwin/debug
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/x86_64-pc-windows-gnu/debug/webrtc-tunnel.exe
          target/debug/webrtc-tunnel
